#!python

__author__='greg timmons'

import sys 
from Sym import Sym

class Attr() : 
    def __init__( self, name, atype ) : 
        self.name = name
       

def repString( sym, x ) :
   return  str(sym.uniq[x]) + ":" + str(x)  

def main( ) :

   attr_count = 0
   pred = Sym()
   

   # load all of lines that are none empty
   inf = [ x for x in map( str.strip, sys.stdin ) if len(x) > 0]

   # load all of the attributes. 
   atr = [ x[11:].split(" ", 1) for x in inf if x[0:10] == "@attribute" ]

   #grab all the none @ lines, these should be data. 
   dat = [ x.split(",") for x in inf if x[0] != "@" ]
  
   attrIndex = len( atr ) - 1

   map( pred.add, [ x[attrIndex] for x in dat ] ) 


   print "=== Predictions on test data ==="
   print ""
   print " inst#     actual  predicted error prediction"
   ln = 1
   for line in dat:
       print ( "%6s %10s %10s %07s" % ( 
             ln,
             repString( pred, line[attrIndex]),
             repString( pred, pred.mode),
             "1" if line[attrIndex] == pred.mode else "0"   
       ))
       ln += 1
       
       


if __name__ == '__main__' : 
   main()
